services:
  - type: web
    name: ts11-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FRONTEND_URL
        value: https://frontend-bnr9.onrender.com

  - type: static
    name: ts11-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_WS_URL
        value: wss://backend-3px5.onrender.com/ws
      - key: VITE_API_URL
        value: https://backend-3px5.onrender.com